apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyternotebooks.squonk.it
spec:
  conversion:
    strategy: None
  group: squonk.it
  names:
    kind: JupyterNotebook
    listKind: JupyterNotebookList
    plural: jupyternotebooks
    singular: jupyternotebook
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: URL for acessing the Jupyter notebook.
      jsonPath: .status.jupyter.notebook.url
      name: URL
      type: string
    - description: Password for accessing the Jupyter notebook.
      jsonPath: .status.jupyter.notebook.password
      name: Password
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              deployment:
                properties:
                  image:
                    type: string
                  resources:
                    properties:
                      limits:
                        properties:
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                      requests:
                        properties:
                          memory:
                            type: string
                          storage:
                            type: string
                        type: object
                    type: object
                  serviceAccountName:
                    type: string
                type: object
              notebook:
                properties:
                  interface:
                    type: string
                type: object
              storage:
                properties:
                  claimName:
                    type: string
                  subPath:
                    type: string
                type: object
            type: object
          status:
            type: object
        type: object
    served: true
    storage: true

