apiVersion: squonk.it/v1alpha1
kind: JupyterNotebook
metadata:
  name: notebook
spec:
  notebook:
    interface: lab
  deployment:
    image: jupyter/minimal-notebook
    serviceAccountName: default
    resources:
      requests:
        storage: 5Gi
      limits:
        memory: 512Mi
